# Generated by Django 3.1 on 2020-09-21 06:21

from django.db import migrations

from core.migrations.Helper.helper import create_fields


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20200825_1452'),
    ]

    operations = [create_fields('Tag')]
