# Generated by Django 3.1 on 2020-09-23 11:57

from django.db import migrations

from core.migrations.Helper.helper import create_fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=create_fields(),
        ),
    ]
